### ISSUE TITLE
Not using hmac.compare_digest

### ISSUE THREAD

**Issue by Compro-Prasad** [nogoodusername/simple-otp#2]
Its recommended to use `hmac.compare_digest` instead of directly comparing using `==`. But I can't see any references to `compare_digest` in your source code.

I don't know for sure if its needed or not but I would like to know why you didn't consider using `hmac.compare_digest`.

References:
1. https://docs.python.org/3/library/hmac.html#hmac.HMAC.hexdigest
2. https://github.com/nogoodusername/simple-otp/search?q=compare_digest

**Comment by nogoodusername** [comment]
Hey, thanks for pointing this out.

Can you send a PR for this?

**Comment by Compro-Prasad** [comment]
@nogoodusername Sent 2 PRs. One fixes this issue. The other PR fixes random number generator issue.
